### ISSUE TITLE
Fullscreen Mode on Windows Experimental Release

### ISSUE THREAD

**Issue by RedBison** [HAL20000/slingshot#2]
When enabling fullscreen in windows experimental release the application crashes without any notifications.
[logfile.txt](https://github.com/HAL20000/slingshot/files/3177449/logfile.txt)

**Comment by HAL20000** [comment]
This is most likely related to inconsisent use of spaces and tabs and the windows interpreter thinking of a different tabstop than the linux interpreter.

**Comment by HAL20000** [comment]
If possible, please check, if this commit resolves the issue
